services:
  api:
    build:
      context: ../../books_api
      dockerfile: Dockerfile
    container_name: books-api-test
    ports:
      - '8080:8080'
    environment:
      - GIN_MODE=release
      - DB_PATH=/data/books.db
    volumes:
      - test_api_data:/data
    healthcheck:
      test:
        [
          'CMD',
          'wget',
          '--no-verbose',
          '--tries=1',
          '--spider',
          'http://localhost:8080/health',
        ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s
    networks:
      - books-test-network

  frontend:
    build:
      context: ../../frontend
      dockerfile: Dockerfile
    container_name: books-frontend-test
    ports:
      - '3000:80'
    depends_on:
      api:
        condition: service_healthy
    healthcheck:
      test:
        [
          'CMD',
          'wget',
          '--no-verbose',
          '--tries=1',
          '--spider',
          'http://localhost/health',
        ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - books-test-network

volumes:
  test_api_data:
    driver: local

networks:
  books-test-network:
    driver: bridge
